apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml

namespace: goapp

images:
- name: goapp
  newTag: v2
  newName: geraldocoosta/goserver-helloworld