apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml

namespace: goapp

images:
- name: goapp
  newName: geraldocoosta/goserver-helloworld
  newTag: 672fb48b246db6d974c09c3decf995d7a51413d5
